### ISSUE TITLE
RBAC based access policies on the Key Vault

### ISSUE THREAD

**Issue by joelverhagen** [Azure/get-keyvault-secrets#25]
This step in the README suggests that Key Vault access policies are the expectation:
https://github.com/Azure/get-keyvault-secrets#enable-permissions-to-access-the-key-vault-secrets

However Key Vault also supports RBAC based permissions. Is this model supported?
https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli

I tried it by giving the service principal "Key Vault Reader" role (21090545-7ca7-4776-b22c-e363652d74d2) but I ran into access denied errors. Switch over to Key Vault access policies resolved the issue.

**Comment by Pwd9000-ML** [comment]
I also have an issue here.
Much rather prefer to use the RBAC model with role `Key vault secrets user`, however this particular action seems to only use Access  policies rather than the newer RBAC model.

**Comment by Pwd9000-ML** [comment]
@joelverhagen This does actually work on the RBAC model.
When you create a key vault, it will by default use the `permission model: Vault Access Policy`
What you need to do is in the azure portal go to `access policies` blade and specifically select the permission model to be `Azure role-based access control`

Or when you create the key vault you can also use CLI with the `--enable-rbac-authorization` option, for example:
```powershell
az keyvault create --name "kvName" --resource-group "rgName" --location "UKSouth" --enable-rbac-authorization
```

[ref](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az_keyvault_create)

**Comment by Pwd9000-ML** [comment]
@joelverhagen This does actually work on the RBAC model.
When you create a key vault, it will by default use the `permission model: Vault Access Policy`
What you need to do is in the azure portal go to access policies blade and specifically select the permission model to be `Azure role-based access control`

Or when you create the key vault you can also use Azure CLI with the `--enable-rbac-authorization` option, for example:

```powershell
az keyvault create --name "kvName" --resource-group "rgName" --location "UKSouth" --enable-rbac-authorization
```

I use this action without access policies, but using the RBAC model instead, see this [refference](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az_keyvault_create) on how to create a keyvault using AZ CLI and using the option `--enable-rbac-authorization`

**Comment by kanika1894** [comment]
Thanks for your inputs @Pwd9000-ML 
@joelverhagen I hope you have better clarity now?

**Comment by kanika1894** [comment]
Please feel free to re-open in case of any queries.
