### ISSUE TITLE
GA Date

### ISSUE THREAD

**Issue by kleeadrian** [Azure/get-keyvault-secrets#27]
Hi Team!

I was wondering when is the date for when this action would be released officially? At the moment it is still in pre-release...

Adrian

**Comment by kaverma** [comment]
Hi @ds-ms , "Support for Azure Stacks" is a pre-release. Can it be marked GA?

**Comment by kaverma** [comment]
Checked with Deepak, the Azure team had validated the scenarios related to Azure stacks. And we can mark the latest release also as GA.

**Comment by kaverma** [comment]
Also @kleeadrian, this Action has been released before, only the latest release with some new features was marked pre-release.

**Comment by kanika1894** [comment]
It's no longer a pre-release. Updated the latest release.✌🏼
